# Generated by Django 2.1.7 on 2020-07-23 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuClas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StuData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('studentClas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherStu.StuClas')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='studentClas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeacherStu.StuClas'),
        ),
        migrations.AddField(
            model_name='news',
            name='studentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeacherStu.StuData'),
        ),
    ]
