# Generated by Django 2.1.7 on 2020-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0004_remove_news_studentclas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studata',
            name='studentClas',
        ),
        migrations.RemoveField(
            model_name='news',
            name='studentType',
        ),
        migrations.AddField(
            model_name='news',
            name='class_code',
            field=models.CharField(choices=[('PREP', 'PREP'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='user_code',
            field=models.CharField(choices=[('ALL', 'ALL'), ('CLASS', 'CLASS'), ('STUDENT', 'STUDENT')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StuClas',
        ),
        migrations.DeleteModel(
            name='StuData',
        ),
    ]
