# Generated by Django 2.1.7 on 2020-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0007_auto_20200723_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
