# Generated by Django 2.1.7 on 2020-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0009_auto_20200723_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='que_Imange',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
