# Generated by Django 2.1.7 on 2020-07-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0010_mcq_question_que_imange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_question',
            old_name='que_Imange',
            new_name='que_Image',
        ),
    ]
