# Generated by Django 2.1.7 on 2020-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0011_auto_20200724_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
