# Generated by Django 2.1.7 on 2020-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0012_mcq_question_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_answer',
            name='que_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
