# Generated by Django 2.1.7 on 2020-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0013_mcq_answer_que_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_answer',
            name='que_Image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='que_Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
