# Generated by Django 2.1.7 on 2020-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0014_auto_20200724_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='flag',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
