# Generated by Django 2.1.7 on 2020-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0015_auto_20200724_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='flag',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='que_Image',
            field=models.URLField(blank=True, default='None', max_length=1000, null=True),
        ),
    ]
