# Generated by Django 2.1.7 on 2020-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0019_auto_20200724_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
