# Generated by Django 2.1.7 on 2020-07-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0020_auto_20200724_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_answer',
            name='que_Image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
