# Generated by Django 2.1.7 on 2020-07-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0021_auto_20200727_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_result',
            name='Studentname',
        ),
        migrations.RemoveField(
            model_name='mcq_result',
            name='correctAnswer',
        ),
    ]
