# Generated by Django 2.1.7 on 2020-07-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0023_mcq_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_post',
            name='id',
        ),
    ]
