# Generated by Django 2.1.7 on 2020-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0024_remove_mcq_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='que_Image',
            field=models.ImageField(default='images/Blank', max_length=1000, upload_to='images/'),
        ),
    ]
