# Generated by Django 2.1.7 on 2020-08-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0027_notesfire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesfire',
            name='pdf_upload',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
