# Generated by Django 2.1.7 on 2020-09-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0031_videoform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videoForm',
            new_name='videoF',
        ),
    ]
