# Generated by Django 2.1.7 on 2020-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0032_auto_20200918_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videof',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
