# Generated by Django 2.1.7 on 2020-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0033_auto_20200918_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='videof',
            name='school',
            field=models.CharField(default='KAS', max_length=3),
            preserve_default=False,
        ),
    ]
