# Generated by Django 2.1.7 on 2020-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0035_noticeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeimage',
            name='clas',
            field=models.CharField(max_length=255),
        ),
    ]
