# Generated by Django 2.1.7 on 2020-07-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserWeb', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='FeedbackUser',
        ),
    ]
