# Generated by Django 2.1.7 on 2020-08-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserWeb', '0003_auto_20200713_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
